// agent/tests/vault_consistency.rs

//! Vault Consistency: Final output validation.
//! Ensures that the JSON generated by Protocol 19 (Temporal Projectile)
//! strictly adheres to the schema expected by the Bridge and integration layers.

use chrono_seo_agent::protocols::SeoSignal;
use chrono_seo_agent::protocols::temporal_projectile::TemporalProjectile;
use serde_json::{json, Value};
use std::fs;
use std::io::Write;
use std::path::Path;

#[tokio::test]
async fn test_vault_schema_integrity() {
    // 1. Setup: Create a controlled signal set including new multi-sector types
    // Testing both standard trends and the new Arbitrage signals.
    let signals = vec![
        SeoSignal::new("Post-Quantum Cryptography".to_string(), 95.0),
        SeoSignal::new("BTC Arbitrage Opportunity".to_string(), 92.0),
    ];

    // 2. Execution: Deploy to the vault path using Protocol 19
    let deployment_result = TemporalProjectile::deploy(signals).await;
    assert!(deployment_result.is_ok(), "Protocol 19 deployment failed during consistency test.");

    // 3. Validation: Locate the vault and verify structural integrity
    // Note: Path is relative to the agent directory during 'cargo test'
    let vault_path = "../vault/truth-vault.json";
    let vault_content = fs::read_to_string(vault_path)
        .expect("Consistency Error: Truth-Vault file not found after deployment.");

    let v: Value = serde_json::from_str(vault_content.trim())
        .expect("Consistency Error: Vault contains invalid JSON structure.");

    // 4. Schema Assertions (Version 1.1.0-PURIFIED)
    // Ensuring all mandatory fields for the Ark-Bridge are present.
    assert_eq!(v["protocol_version"], "1.1.0-PURIFIED");
    assert!(v.get("pulse_timestamp").is_some(), "Missing field: pulse_timestamp");
    assert!(v.get("signals_count").is_some(), "Missing field: signals_count");
    assert!(v.get("data").is_some(), "Missing field: data");

    // Verify signals_count matches the deployed vector length
    if let Some(count) = v["signals_count"].as_u64() {
        assert_eq!(count, 2, "Signals count mismatch in Vault metadata.");
    }
}

#[test]
fn test_vault_atomic_overwrite_integrity() {
    // FIX: Using a isolated path to prevent collision with live pulse operations
    let path = "../vault/truth-vault-atomic-test.json";
    
    if let Some(parent) = Path::new(path).parent() {
        fs::create_dir_all(parent).unwrap();
    }
    
    // 1. Scenario: Simulate a corrupted or legacy large file
    let legacy_junk = "{\"old_junk\": \"".to_owned() + &"X".repeat(5000) + "\"}"; 
    fs::write(path, legacy_junk).unwrap();

    // 2. Define the expected purified structure
    let expected_json = json!({
        "pulse_timestamp": "2026-04-21T00:00:00Z",
        "protocol_version": "1.1.0-PURIFIED",
        "signals_count": 0,
        "data": []
    });

    // 3. Execution: Perform atomic-style truncate and write
    {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true) 
            .open(path)
            .expect("Failed to open test vault with truncate");

        let payload = serde_json::to_string_pretty(&expected_json).unwrap();
        file.write_all(payload.as_bytes()).expect("Failed to write payload");
        file.sync_all().expect("File system sync failed");
    }

    // 4. Validation
    let final_content = fs::read_to_string(path).expect("Failed to read test vault");
    let final_json: Value = serde_json::from_str(final_content.trim())
        .expect("Consistency Error: Trailing artifacts detected after truncate.");
    
    assert_eq!(final_json, expected_json, "Atomic overwrite failure: Data corruption detected.");

    // Cleanup: Securely remove the temporary test file
    let _ = fs::remove_file(path);
}
